#!/usr/bin/env bash

# SPDX-FileCopyrightText: 2026 Xquik contributors
#
# SPDX-License-Identifier: Apache-2.0

set -e

cd "$(dirname "$0")/.."

echo "==> Checking types"
./node_modules/typescript/bin/tsc --project tsconfig.json --noEmit


echo "==> Running tests"
./node_modules/.bin/jest "$@"
